### ISSUE TITLE
Saving result in a diff file ? 

### ISSUE THREAD

**Issue by sucrecacao** [dmerejkowsky/ruplacer#48]
Would it be possible to save the in a `.diff` file ? So it's possible to with `git apply foo.diff` to apply the change ?

If not, could you give a few pointers on which part of the code I should look at to add this feature ?

**Comment by dmerejkowsky** [comment]
Well, there's a DirectoryPatcher struct whose job is to find the source files, and a FilePatcher struct to compute and apply patches to each file one by one. I guess we could split `main()` and either re-use the FilePatcher or write a new struct to write the replacements to a `.diff` file.

Not sure what's your use case, though. I usually use ruplacer like this:

```
$ git status
# Make sure no change neds to be committed
$ ruplacer foo bar
# Make sure the diff looks ok
$ ruplacer foo bar --go
$ git add .
$ git commit -m "Replace foo with bar"
```

In your case, you could replace the `git add .` command with `git diff HEAD~1 > foo.diff` and that would produce the file you want, so I'm not sure the feature you're asking is useful.

Do tell me if I missed something, though.

**Comment by dmerejkowsky** [comment]
By the way, I can add something about #44 - I guess you could achieve the "selection feature" by using `git add -p` instead of `git add`.

In other words, let ruplacer write changes to the file system, and let git handle the diffs :)
