### ISSUE TITLE
How to use Ruplacer in another function

### ISSUE THREAD

**Issue by pin-contract** [dmerejkowsky/ruplacer#53]
I've tried to write an function:
```
fn run_ruplacer(path, foo, bar) {
   
}
```

but can not, is there any one can help me?

**Comment by dmerejkowsky** [comment]
I'm not sure I understand your question. Do you want to use ruplacer's functionality from an other Rust program? Or to put it in an other way, do you want to use ruplacer's code as a library?

Ruplacer was not designed to be used as a library, but it should still be possible.

You can take a look at `src/main.rs` for inspiration.

Basically, you'll have to build a `Settings` struct, a `Query` struct and do something like this:

```rust
let settings = ruplacer::Settings::default();
let query = ruplacer::query::substring("foo", "bar");
let mut directory_patcher = ruplacer::DirectoryPatcher::new(path, settings);
let outcome = directory_patcher.run(&query);
```

**Comment by dmerejkowsky** [comment]
Note that if you _do_ want to use ruplacer as a library, we could also add more code in `src/lib.rs` so that it's a bit easier to use and less likely to break. Currently, the code that I showed you might break in the future.

**Comment by dmerejkowsky** [comment]
Hi @pin-contract, I have some good news.

I've been working on a better public API. It's still a beta, but I appreciate it if you could take a look.

Here's how to patch source files in a directory:

https://docs.rs/ruplacer/0.6.0-beta1/ruplacer/struct.DirectoryPatcher.html

And you can also replace in arbitrary text:

https://docs.rs/ruplacer/0.6.0-beta1/ruplacer/fn.replace.html

**Comment by dmerejkowsky** [comment]
Going to close this. Feel free to open a new issue if the new API does not work for you.

(Version 0.6.0 is out)
