### ISSUE TITLE
Feature request: filter files by regexp

### ISSUE THREAD

**Issue by s-d-m** [dmerejkowsky/ruplacer#56]
Currently ruplacer provides a `-t` option to let work only on a file type, like c++, java, gradle ...
It would be nice if the user could provide a regexp to match against specific files and only check those.

**Comment by dmerejkowsky** [comment]
Why not :)

the `WalkBuilder` struct from the `ignore` crrate we use has a `filter_entry` method we could use for this purpose, along with a `--file-regex` flag or something.
