### ISSUE TITLE
Possible wrong implementation of --ignored flag

### ISSUE THREAD

**Issue by ndtoan96** [dmerejkowsky/ruplacer#61]
In the help, it says that if `--ignored` flag is `true`, ruplacer will patch ignored files too. But current implementation and test case is the opposite. [This](https://github.com/dmerejkowsky/ruplacer/blob/80d523b55c44cb778b6fdb1749775d8524441706/src/directory_patcher.rs#L95-L96) has no effect because `ignore::WalkBuilder::ignore` is already set to `true` by default.

**Comment by dmerejkowsky** [comment]
My bad :)
