### ISSUE TITLE
Error: nothing found to replace

### ISSUE THREAD

**Issue by sergeevabc** [dmerejkowsky/ruplacer#63]
Source: [koi8-r.zip](https://github.com/dmerejkowsky/ruplacer/files/6393643/koi8-r.zip)

``` console
$ ruplacer "<meta.*?charset=.*?>" $1 koi8-r.htm
Error: nothing found to replace 
```

but, hey, there is something to replace as follows
``` console
$ rg "<meta.*?charset=.*?>" koi8-r.htm
4:<META content="text/html; charset=koi8-r" http-equiv=Content-Type>
```

**Comment by dmerejkowsky** [comment]
Interesting. On my machine, `rg` does not find anything either.

Note that the file in `.htm` is *not* encoded in UTF-8.

How did you install `rg` ? Which version is it? On what operating system are you running this?
