### ISSUE TITLE
Replacement with empty string

### ISSUE THREAD

**Issue by gpoore** [dmerejkowsky/ruplacer#68]
Thanks for creating ruplacer! It's been great for renaming variables across source files.

Is there a way to replace matches with the empty string? For example,
```
ruplacer "string" ""
```
fails with
```
error: The following required arguments were not provided:
    <replacement>
```
I've been working around this by just adding an empty capture group `()` and then replacing with `'$1'`.

**Comment by dmerejkowsky** [comment]
Sorry but I can't reproduce that bug here. What operating system and what kind of terminal are you using here ?

**Comment by gpoore** [comment]
I did some additional checking, and my issue is due to a longstanding bug in PowerShell:
* https://github.com/PowerShell/PowerShell/issues/6280
* https://github.com/PowerShell/PowerShell/issues/14747

So Ruplacer is working correctly...and now I have to worry about shell bugs whenever something doesn't work as expected!
