### ISSUE TITLE
Question: Is there a tool as smoking hot as Ruplacer, but for file renames?

### ISSUE THREAD

**Issue by snoblenet** [dmerejkowsky/ruplacer#80]
I'd like to add an alias to my `~/.zshrc` that calls Ruplacer and this other tool one after the other with the same parameters...

**Comment by dmerejkowsky** [comment]
Thanks for the compliment ;)

Personally I use `vidir` from the `moreutils` package.

`lf` and `batch` offer similar functionality too.

**Comment by snoblenet** [comment]
Thanks I will check them out.
