### ISSUE TITLE
Outdated version in brew

### ISSUE THREAD

**Issue by Masynchin** [dmerejkowsky/ruplacer#82]
While trying to apply "--ignored" option I discovered that my version is 0.4.1 while newest is 0.6.4. I can't install if from assets (macOS warns me about it), but will try to install from source. It would be much easier to me if you will update your brew package version. Thanks.

**Comment by Masynchin** [comment]
I install it (having rust and cargo installed) with:

~~~zsh
gh repo clone dmerejkowsky/ruplacer
cd ruplacer
cargo install replacer
~~~

After that I add cargo binaries to PATH:

~~~
# ~/.zshrc
export PATH="$PATH:/Users/<username>/.cargo/bin"
~~~

And update zsh:

~~~zsh
. ~/.zshrc
~~~

**Comment by dmerejkowsky** [comment]
Well, I no longer have access to Apple hardware, so I won't be able to maintain the homebrew recipe.

Glad you found a workaround, though.

**Comment by dmerejkowsky** [comment]
See: https://github.com/dmerejkowsky/homebrew-repo/issues/11

**Comment by dmerejkowsky** [comment]
@maximerety < your turn ;)

**Comment by maximerety** [comment]
Here you go: https://github.com/dmerejkowsky/homebrew-repo/pull/12
