### ISSUE TITLE
Feature request : add 'quiet' option

### ISSUE THREAD

**Issue by kpym** [dmerejkowsky/ruplacer#87]
It will be nice to have `-q/--quiet` option to use in conjunction with `--go`. Or may be `--qgo` (for "quiet go").

**Comment by dmerejkowsky** [comment]
I prefer a separate `--quiet` argument - this is consistent with many other tools.

Do you want to try and submit a patch ?

**Comment by kpym** [comment]
@dmerejkowsky I would love to, but rust is not part of my skill set, sorry. 😳

**Comment by dmerejkowsky** [comment]
Well, turned out it was a bit more difficult than I though it would be.

Also, fun fact, I messed up my working copy by running `ruplacer --go --quiet` with the wrong folder. So ... be careful with the combination of the two options ;)

**Comment by dmerejkowsky** [comment]
Anyhow, this has been implement in the 0.7.0 release. Enjoy!

**Comment by kpym** [comment]
Thanks for considering this and do it so quickly. 🙏 
I was thinking that this will be as simple to replace `stdout` by `null` and keep `stderr` as is... but it is never as simple as we think. 😉
