### ISSUE TITLE
Expose case-insensitive processing of `ignore` files?

### ISSUE THREAD

**Issue by ErichDonGubler** [dmerejkowsky/ruplacer#92]
The `ignore` crate provides an [API](https://docs.rs/ignore/0.4.18/ignore/struct.WalkBuilder.html#method.ignore_case_insensitive) for processing `ignore`-relevant files case-insensitively. Is this interesting to expose to end users?

**Comment by dmerejkowsky** [comment]
I don't think so, unless you have a very specific use case in mind.

If ruplacer replaces too much stuff it's pretty easy to use `git add/git restore` to restore the files that should not have changed.
